export const GETPRODECTLOADED = 'GETPRODECTLOADED';
export const GETPRODECTLOADING = 'GETPRODECTLOADING';

export const LOCATION_DATA_LOADING = 'LOCATION_DATA_LOADING';
export const LOCATION_DATA_SUCCESS = 'LOCATION_DATA_SUCCESS';
export const LOCATION_DATA_FAIL = 'LOCATION_DATA_FAIL';

export const WATHER_DATA_LOADING = 'WATHER_DATA_LOADING';
export const WATHER_DATA_SUCCESS = 'WATHER_DATA_SUCCESS';
export const WATHER_DATA_FAIL = 'WATHER_DATA_FAIL';

export const WATHER_FORECAST_LOADING = 'WATHER_FORECAST_LOADING';
export const WATHER_FORECAST_SUCCESS = 'WATHER_FORECAST_SUCCESS';
export const WATHER_FORECAST_FAIL = 'WATHER_FORECAST_FAIL';

export const WATHER_DAILY_LOADING = 'WATHER_DAILY_LOADING';
export const WATHER_DAILY_SUCCESS = 'WATHER_DAILY_SUCCESS';
export const WATHER_DAILY_FAIL = 'WATHER_DAILY_FAIL';

export const WATHER_ONECALL_LOADING = 'WATHER_ONECALL_LOADING';
export const WATHER_ONECALL_SUCCESS = 'WATHER_ONECALL_SUCCESS';
export const WATHER_ONECALL_FAIL = 'WATHER_ONECALL_FAIL';

