export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCT_RESET = 'GET_PRODUCT_RESET';

export const GET_DETAIL_FAIL = 'GET_DETAIL_FAIL';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_LOADING = 'GET_DETAIL_LOADING';
export const GET_DETAIL_RESET = 'GET_DETAIL_RESET';

export const DELETE_FAIL = 'DELETE_FAIL';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_LOADING = 'DELETE_LOADING';
export const DELETE_RESET = 'DELETE_RESET';

export const UPDATE_FAIL = 'UPDATE_FAIL';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_LOADING = 'UPDATE_LOADING';

export const POST_FAIL = 'POST_FAIL';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_LOADING = 'POST_LOADING';

